### PR TITLE
Normalize spaces around var tags

### LINKED ISSUE #23: Give flexibility to spaces before/after var tags
I figured out some test cases are failing because of spaces again.
Few weeks ago we fixed the spacing issue around optional tags, but now we need to do the same thing again around var tags.

This is an example failure case from Apache license:

regex:
```
if`such`contributor`has`been`advised`of`the`possibility`of`such`damages\.`(?:.{0,20})`accepting`warranty`or`additional`liability\.
```

input:
```
if`such`contributor`has`been`advised`of`the`possibility`of`such`damages.`accepting`warranty`or`additional`liability.
```

We see only a single space(backtick) between `damages.` and `accepting`, but the regex requires at least two spaces.

My plan is to modify normalizer and replace spaces before/after var tags with "optional" spaces.

Cc: @goneall, @anshuldutt21

### PR DESCRIPTION
**Pull request by m1kit**
This fixes #23

### CODE REVIEW

**Comment by m1kit** [comment]
I added optional spaces before/after var tags, and it fixed the issue with the Apache License.

However, probably due to this change, a test with GPL takes tooooo long so that the entire test process is timed out. 
I want to keep this PR as a draft at this moment, and add time-out mechanics to the license detector.

The mechanics would be like:
- Users can specify `time_out` parameter on detection (or left it as `None` to allow detector to spend infinity time`)
  - My idea for default value is 100ms to 1000ms
- Do license detection as before unless single regex test takes over `time_out`.
- If it exceeds `time_out`, skip the test and report it.

(FYI, I think this idea is related to #12)

Cc: @goneall, @anshuldutt21

**Comment by goneall** [comment]
> a test with GPL takes tooooo long so that the entire test process is timed out

I wonder if we have [catastrophic backtracking](https://www.regular-expressions.info/catastrophic.html) problem with the GPL license.  

In a quick look at the license XML, I noticed an alt tag with this regex: ` <alt name="copyright" match=".+">`

Since it is unbounded, it could have a lot of back-tracking.

A fix to the License XML would be to change the regex to `.{1,500}` to limit the backtracking to a reasonable copyright length.

There are probably a lot of cases where we have regexes in license XML like `.+` or `'.*`.

One solution in the matcher or in the licenseRdfaGenerator would be to insert a limit for a maximum license length whenever we find such an unbounded regex.  It would be a bit hacky, but it may  avoid some of these issues.

**Comment by m1kit** [comment]
@goneall

> I wonder if we have catastrophic backtracking problem with the GPL license.
I agree, and potentially other licenses can produce the problem too. We had better support time-out to prevent ReDoS attacks. (DoS to regex engine)

> One solution in the matcher or in the licenseRdfaGenerator would be to insert a limit for a maximum license length 
It's a good idea, there are about 165 occurences of `.+` across all the license templates. Maybe we can replace them easily with terregex.

Such regular expressions are too flexible, and I think it would be desirable to eliminate them from the license templates after discussion with the community.

**Comment by goneall** [comment]
> We had better support time-out to prevent ReDoS attacks. (DoS to regex engine)

Agree

> Such regular expressions are too flexible, and I think it would be desirable to eliminate them from the license templates in future, after discussion with the community.

We'll need some way to handle variable text matching in the license - perhaps introducing some restrictions on the regexes.  There are also some regex testing algorithms that can detect catastrophic backtracking.  Perhaps we can add a check to the Github action on the LicenseList-XML repo to check for these regexes or add a check in the LicenseListPublisher which gets run by the Github action.

**Comment by m1kit** [comment]
It seems the spacing issue with Apache license is resolved. Going to merge this

**Pull request merged**
