### PR TITLE
Feature: structured template

### LINKED ISSUE #7: Pre-generate regex
This issue is a part of #1 .

Currently, the templates are normalized first, and then the var tags are parsed. However, this method may cause the regular expression contained in the var tag to be transformed during normalization. ~~In fact, the current implementation deals with this by skipping some of the normalization steps for templates.~~

I think it is better to parse var tags first, and then normalize only the plain text excluding regular expressions.

### PR DESCRIPTION
**Pull request by m1kit**
This will close #7, also add a draft API for license matching

### CODE REVIEW

**Comment by anshuldutt21** [comment]
Good work @m1kit. Did a quick glance. Just wanted to confirm and add a couple of things. 
1. After handling the Omitable and Replaceable text in the JSON, are we ensuring that more than 1 consecutive backticks '`' are removed wherever possible, since while handling the omitable text, there needs to be a space before and after the optional tags which needs to get replaced by backticks. So it might be a good idea to check and eliminate this scenario to avoid neglecting a possible match.
2. Can you briefly explain the strategy used to handle the omitable and replaceable text: i.e are you converting the entire part to regex excluding the <<var>> regex part. I just need to confirm whether the escape characters specified in the var regex are not disturbed by the regex conversion.
3. Handling multiple things in the code, I think it would be better for you in the long run if you maintain a checklist and start striking out the stuff that you complete as a separate issue.

**Comment by m1kit** [comment]
> 1. After handling the Omitable and Replaceable text in the JSON, are we ensuring that more than 1 consecutive backticks '`' are removed wherever possible, since while handling the omitable text, there needs to be a space before and after the optional tags which needs to get replaced by backticks. So it might be a good idea to check and eliminate this scenario to avoid neglecting a possible match.

Handling of spaces is one big task I'm working on, and trying to keep "the rule" as simple as possible. 
I hope to consider only `spacing` attribute on the XMLs, just follow the instruction by it.
Even with only this rule, the library can work correctly, but maybe this requires XML creaters to be careful about handling of spaces.

e.g.
Let's think about a license template which matches one of the following:
`I like an apple.`
`I like an apple and an orange.`

This template may seem correct, but not if we use the simple rule.
```
<p>I like an apple <optional>and an orange</optional>.</p>
```
We automatically insert a single space after `<optional>` since it is default behavior of `spacing` attribute.
So this template is equivalent to:
```
<p>I like an apple <optional> and an orange</optional>.</p>
```
And this can lead to mismatch due to consecutive spaces between `apple` and `and`.

Correct template should be like
```
<p>I like an apple<optional> and an orange</optional>.</p>
```
I feel like this can be confusing when someone adds a new XML.

One possible solution is, ignore `spacing` attribute and just insert an optional single space before/after an optional tag (I think this is the approach you did). This is the simplest for everyone but we may lose a way to explicitly deny an extra space in a template.

Another solution is, to move some spaces automatically.
I think we can move spaces before `<optional>` to after it, and spaces before `</optional>` to after it. By doing this we can encourage templates to follow the default behavior of `spacing` attribute.





> 2. Can you briefly explain the strategy used to handle the omitable and replaceable text: i.e are you converting the entire part to regex excluding the << `var` >> regex part. I just need to confirm whether the escape characters specified in the var regex are not disturbed by the regex conversion.

At this moment, the regex is not normalized at all. I'm sure regex is not corrupted.
I agree we need some discussion on this part, since this strategy requires regexes in a template to be wrtten in a normalized form (e.g. no consecutive spaces in regex).

> 3. Handling multiple things in the code, I think it would be better for you in the long run if you maintain a checklist and start striking out the stuff that you complete as a separate pull request. It might also be a good idea to start editing the documentation a little bit from now onwards.
I agree with all your comments here.

**Comment by goneall** [comment]
> One possible solution is, ignore spacing attribute and just insert an optional single space before/after an optional tag (I think this is the approach you did). This is the simplest for everyone but we may lose a way to explicitly deny an extra space in a template.

I think this might be the best approach.  The spacing attribute was introduced to solve a display problem and matching wasn't as much of a consideration.  I would expect a lot of the `<optional>` tags to have incorrect spacing attributes.

**Comment by m1kit** [comment]
@goneall @anshuldutt21 
Hello,

By adding space trimming rule before/after optional tags, the core feature - license detection seems to be working now.
I think the long journey to introduce new structured strategy is almost completed.

As we discussed before, I need to set up automatic tests for qualitative assessment, but it is another issue.
I'd like to merge this PR and move forward.
If you notice any mistake or request, please write here.

Thanks

**Review by goneall — APPROVED** [review]
LGTM

**Comment by goneall** [comment]
@m1kit I reviewed the changes and they all looked good.  I agree with your proposal to merge the PR one @anshuldutt21 has a chance to review.

**Comment by anshuldutt21** [comment]
@m1kit I reviewed the changes and it looks good to me as well. I think we can merge this PR.

**Pull request merged**
